[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "install-all"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[trios-dwagent]
memory = 256
cpu = 0.5
